// Product data array
// Add your products here with the format below
const products = [
  {
    id: 1,
    collection: "50 ml collection",
    name: "Velvet Bloom",
    description:
      "A luxurious floral fragrance that captures the essence of blooming flowers in spring. Soft, elegant, and undeniably feminine, Velvet Bloom wraps you in a delicate embrace of petals and warmth.",
    originalPrice: "PKR 3,750",
    price: "PKR 3,399",
    images: ["images/vb1.jpeg", "images/vb2.jpeg", "images/vb3.jpeg"],
  },
  {
    id: 2,
    collection: "50 ml collection",
    name: "Oud Noor",
    description:
      "A rich and captivating Oud fragrance that radiates warmth and sophistication. Blending traditional deep woody notes with a modern touch of light, Oud Noor is perfect for those who appreciate timeless elegance.",
    originalPrice: "PKR 3,699",
    price: "PKR 3,199",
    images: ["images/on1.jpeg", "images/on2.jpeg", "images/on3.jpeg"],
  },
  {
    id: 3,
    collection: "50 ml collection",
    name: "Strong With You",
    description:
      "A charismatic and addictive fragrance for men. Spicy accords of pink pepper and cardamom mix with the sweetness of glazed chestnut and vanilla, creating a scent that is both strong and inviting.",
    originalPrice: "PKR 3,999",
    price: "PKR 3,599",
    images: ["images/swy1.jpeg", "images/swy2.jpeg", "images/swy3.jpeg"],
  },
  {
    id: 5,
    collection: "50 ml collection",
    name: "Midnight Valor",
    description:
      "Intense, mysterious, and bold. Midnight Valor is a fragrance for the night, featuring deep notes of leather, amber, and dark woods. A scent for the brave who thrive when the sun goes down.",
    originalPrice: "PKR 3,750",
    price: "PKR 3,099",
    images: ["images/mv1.jpeg", "images/mv2.jpeg", "images/mv3.jpeg"],
  },
  {
    id: 4,
    collection: "50 ml collection",
    name: "Executive Aura",
    description:
      "Designed for the modern leader, Executive Aura exudes confidence and power. Crisp citrus top notes blend seamlessly with a heart of aromatic spices and a base of solid wood, making it the perfect scent for the boardroom and beyond.",
    originalPrice: "PKR 4,799",
    price: "PKR 4,499",
    images: ["images/ea1.jpeg", "images/ea2.jpeg", "images/ea3.jpeg"],
  },
  {
    id: 6,
    collection: "35 ml collection",
    name: "Inspired by Sauvage Dior",
    description:
      "A fresh and confident scent profile with bright citrus and clean woody depth for everyday wear.",
    originalPrice: "PKR 1,699",
    price: "PKR 1,399",
    images: ["images/sd1.jpeg", "images/sd2.jpeg", "images/sd3.jpeg"],
  },
  {
    id: 7,
    collection: "35 ml collection",
    name: "Inspired by Erba Pura",
    description:
      "A vibrant fruity-musky blend with a soft sweet trail that feels energetic and modern.",
    originalPrice: "PKR 1,699",
    price: "PKR 1,399",
    images: ["images/ep1.jpeg", "images/ep2.jpeg", "images/ep3.jpeg"],
  },
  {
    id: 8,
    collection: "35 ml collection",
    name: "Inspired by Gucci Flora",
    description:
      "A graceful floral composition that feels elegant, airy, and perfect for day to evening transitions.",
    originalPrice: "PKR 1,699",
    price: "PKR 1,399",
    images: ["images/gf1.jpeg", "images/gf2.jpeg", "images/gf3.jpeg"],
  },
  {
    id: 9,
    collection: "35 ml collection",
    name: "Inspired by Bleu de Chanel",
    description:
      "A crisp aromatic profile with citrus freshness and smooth woods for a polished signature scent.",
    originalPrice: "PKR 1,699",
    price: "PKR 1,399",
    images: ["images/bdc1.jpeg", "images/bdc2.jpeg", "images/bdc3.jpeg"],
  },
  {
    id: 10,
    collection: "35 ml collection",
    name: "Inspired by Aventus Creed",
    description:
      "A bold fruity-woody character with smoky undertones, crafted for strong presence and longevity.",
    originalPrice: "PKR 1,699",
    price: "PKR 1,399",
    images: ["images/ac1.jpeg", "images/ac2.jpeg", "images/ac3.jpeg"],
  },
  {
    id: 11,
    collection: "Ouds",
    name: "Versace Bright",
    description:
      "Fresh bright character with clean citrus facets and a smooth woody finish.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/ovb1.jpeg", "images/ovb2.jpeg"],
  },
  {
    id: 12,
    collection: "Ouds",
    name: "Havoc",
    description:
      "A bold modern profile with energetic top notes and warm depth.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/oh1.jpeg", "images/oh2.jpeg"],
  },
  {
    id: 13,
    collection: "Ouds",
    name: "Shay Oudh",
    description:
      "Soft oud signature balanced with gentle spice and refined sweetness.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/oso1.jpeg", "images/oso2.jpeg"],
  },
  {
    id: 14,
    collection: "Ouds",
    name: "Sauvage Dior",
    description:
      "Crisp aromatic intensity with strong projection and lasting freshness.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/osd1.jpeg", "images/osd2.jpeg"],
  },
  {
    id: 15,
    collection: "Ouds",
    name: "Gucci Rush",
    description:
      "A vibrant expressive scent with sweet spice and creamy undertones.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/ogr1.jpeg", "images/ogr2.jpeg"],
  },
  {
    id: 16,
    collection: "Ouds",
    name: "Al Faris",
    description: "Classic eastern feel with rich woods and amber warmth.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/oaf1.jpeg", "images/oaf2.jpeg"],
  },
  {
    id: 17,
    collection: "Ouds",
    name: "Bleu D Channel",
    description:
      "Clean masculine style with bright citrus and smoky woody layers.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/obdc1.jpeg", "images/obdc2.jpeg"],
  },
  {
    id: 18,
    collection: "Ouds",
    name: "Tea Rose",
    description: "Delicate rose-forward composition with soft musky nuance.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/otr1.jpeg", "images/otr2.jpeg"],
  },
  {
    id: 19,
    collection: "Ouds",
    name: "Boom Shell",
    description: "Striking character with sweet fruity lift over warm woods.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/obs1.jpeg", "images/obs2.jpeg"],
  },
  {
    id: 20,
    collection: "Ouds",
    name: "Dunhill Desire",
    description: "Smooth and confident blend with spicy facets and amber base.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/odd1.jpeg", "images/odd2.jpeg"],
  },
  {
    id: 21,
    collection: "Ouds",
    name: "White Oudh",
    description: "A lighter oud expression with airy florals and creamy woods.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/owo1.jpeg", "images/owo2.jpeg"],
  },
  {
    id: 22,
    collection: "Ouds",
    name: "Jannan J.",
    description: "Elegant oriental profile with subtle spice and refined musk.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/ojj1.jpeg", "images/ojj2.jpeg"],
  },
  {
    id: 23,
    collection: "Ouds",
    name: "Zarrar J.",
    description:
      "A deep sophisticated tone with woody warmth and smooth finish.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/ozj1.jpeg", "images/ozj2.jpeg"],
  },
  {
    id: 24,
    collection: "Ouds",
    name: "Gucci Flora",
    description:
      "Floral brightness wrapped in a soft musky trail for daily wear.",
    originalPrice: "PKR 999",
    price: "PKR 599",
    images: ["images/ogf1.jpeg", "images/ogf2.jpeg"],
  },
];
